server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: bt-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bt-ms-accounts
          uri: lb://bt-ms-accounts
          predicates:
            - Path=/ms-accounts/**
          filters:
            - RewritePath=/ms-accounts/(?<x>.*), /$\{x}